'use server'

import { revalidatePath } from 'next/cache'
import { createServerClient, createServiceRoleClient } from './supabase/server'

export async function createWebDistribution(surveyId: string) {
  const supabase = await createServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const orgId = user.app_metadata?.organization_id as string | undefined
  if (!orgId) return { error: 'No organization found' }

  const serviceClient = createServiceRoleClient()

  // Check for an existing active web_link distribution
  const { data: existing } = await serviceClient
    .from('survey_distributions')
    .select('id, token')
    .eq('survey_id', surveyId)
    .eq('channel', 'web_link')
    .eq('is_active', true)
    .single()

  if (existing) {
    const row = existing as unknown as { id: string; token: string }
    return { token: row.token, surveyId }
  }

  // Create a new distribution row — token is auto-generated by DB default
  const { data, error } = await serviceClient
    .from('survey_distributions')
    .insert({
      survey_id: surveyId,
      organization_id: orgId,
      channel: 'web_link',
      name: 'Web link',
      is_active: true,
    } as never)
    .select('id, token')
    .single()

  if (error || !data) return { error: error?.message ?? 'Failed to create distribution' }

  const row = data as unknown as { id: string; token: string }

  // Activate the survey so the runner lets respondents through
  await serviceClient
    .from('surveys')
    .update({ status: 'active' } as never)
    .eq('id', surveyId)
    .is('deleted_at', null)

  revalidatePath(`/surveys/${surveyId}/build`)
  return { token: row.token, surveyId }
}

export async function deactivateDistribution(surveyId: string, token: string) {
  const supabase = await createServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const serviceClient = createServiceRoleClient()

  await serviceClient
    .from('survey_distributions')
    .update({ is_active: false } as never)
    .eq('token', token)

  // Set survey back to draft if no active distributions remain
  const { count } = await serviceClient
    .from('survey_distributions')
    .select('id', { count: 'exact', head: true })
    .eq('survey_id', surveyId)
    .eq('is_active', true)

  if (count === 0) {
    await serviceClient
      .from('surveys')
      .update({ status: 'draft' } as never)
      .eq('id', surveyId)
  }

  revalidatePath(`/surveys/${surveyId}/build`)
  return { ok: true }
}
